platform: linux

image_resource:
  type: docker-image
  source: {repository: bosh/main}

inputs:
- name: bosh-linux-stemcell-builder
- name: pipelines
- name: bosh-cli
- name: stemcell
- name: syslog-release
- name: os-conf-release
- name: director-state

params:
  BOSH_os_name: required
  package: .

run:
  path: pipelines/shared/tasks/test-stemcell.sh
